Update lambda emailer demos

diff --git a/demos/lambdaApiGatewayEmailer/_lambda_manager b/demos/lambdaApiGatewayEmailer/_lambda_manager
--- a/demos/lambdaApiGatewayEmailer/_lambda_manager
+++ b/demos/lambdaApiGatewayEmailer/_lambda_manager
@@ -3,28 +3,34 @@
 # Lets you build/analyse lambda function
 
 # Preliminaries
+source .env
 clear
-option=$1
 
-if [[ -z $option ]]; then
+#######################################
+# Crude helper printout
+# Globals:
+#   None
+# Arguments:
+#   None
+#######################################
+function _usage() {
   clear
-  echo """
-    ============================================================
-    LAMBDA FUNCTION MANAGER
+  echo -e """
+    Usage:
+    _lamba_manager help      -   Show usage
+    _lamba_manager build     -   Build bundle
+    _lamba_manager analyze   -   Run webpack bundle analyzer
+  """
+}
 
-    CHOOSE ONE OF THE FOLLOWING OPTIONS
-    (N.b. numbers can be passed directly to script as argument)
-
-    1. Build and zip lambda function
-    2. Examine build with webpack-bundle-analyzer
-
-    ============================================================
-"""
-  read choice
-  option=$choice
-fi
-
-function build_lambda() {
+#######################################
+# Run webpack to build bundle
+# Globals:
+#   None
+# Arguments:
+#   None
+#######################################
+function _build_lambda() {
   # Refresh dist-dir
   rm -rf dist-lambda
   mkdir dist-lambda
@@ -45,22 +51,43 @@ function build_lambda() {
     };
 EOF
 
-}
-
-# Ensure chosen option is a number between 1 and 2
-[[ ! $option =~ ^[0-9]+$ || $option -lt 1 || $option -gt 2 ]] &&
-  echo -e "${RED}Chosen option ("$option") was NOT a number between 1 and 2${WHI}" &&
-  exit 1
-
-if [[ $option -eq 1 ]]; then
-  echo ">>> Building Lambda-Function Bundle ..."
-  build_lambda
+  # Zip output
   cd dist-lambda
   zip exports.js.zip exports.js lambda.js
   cd ..
-fi
 
-if [[ $option -eq 2 ]]; then
-  echo ">>> Analyzing Lambda Bundle ..."
+}
+
+#######################################
+# Run webpack bundle analyzer
+# Globals:
+#   None
+# Arguments:
+#   None
+#######################################
+function _analyze_lambda() {
   ./node_modules/.bin/webpack-bundle-analyzer ./dist-lambda/compilation-stats.json
-fi
+}
+
+main() {
+
+  case "$1" in
+  "--help" | "help")
+    _usage
+    ;;
+  "build")
+    _build_lambda
+    ;;
+  "analyze")
+    _analyze_lambda
+    ;;
+  *)
+    echo >&2 "Invalid option: $@"
+    _usage
+    return 1
+    ;;
+  esac
+
+}
+
+main $@
